global:
  scrape_interval:     15s

rule_files:
- /cfg/rules.yaml
- /cfg/alerts.yaml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: node
    static_configs:
      - targets: ["node_exporter:9100"]
  - job_name: example-app
    static_configs:
      - targets: ["example-app:8080"]
        labels:
          env: test
