services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    pid: host
    ports:
      - "9100:9100"
    volumes:
      - '/:/host:ro'
    command:
      - --path.rootfs=/host
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus-cfg.yaml:/etc/prometheus/prometheus.yml"
      - "prometheus_data:/prometheus"
  test-app:
    image: quay.io/brancz/prometheus-example-app:v0.5.0
    container_name: test-app
    ports:
      - "8080:8080"
  prod-app:
    image: quay.io/brancz/prometheus-example-app:v0.5.0
    container_name: prod-app
    ports:
      - "8081:8080"

volumes:
  prometheus_data: