global:
  scrape_interval:     15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: node
    static_configs:
      - targets: ["node_exporter:9100"]
  - job_name: test-app
    static_configs:
      - targets: ["test-app:8080"]
        labels:
          env: test
  - job_name: prod-app
    static_configs:
      - targets: ["prod-app:8080"]
        labels:
          env: prod