global:
  smtp_smarthost: 'mailhog:1025'
  smtp_from: 'alertmanager@example.org'
  smtp_require_tls: false

route:
  group_by: ['service']
  group_wait: 30s
  group_interval: 15s
  receiver: 'team-X-mail'
  routes:
  - receiver: 'team-X-mail'
    continue: true
  - receiver: 'webhook'
    continue: true

receivers:
  - name: 'webhook'
    webhook_configs:
      - url: 'https://monitoring.requestcatcher.com/test'
  - name: 'team-X-mail'
    email_configs:
      - send_resolved: false
        to: 'foo@example.org'