services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    pid: host
    volumes:
      - '/:/host:ro'
    command:
      - --path.rootfs=/host
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus-cfg.yaml:/etc/prometheus/prometheus.yml"
      - "./rules.yaml:/cfg/rules.yaml"
      - "./alerts.yaml:/cfg/alerts.yaml"
      - "prometheus_data:/prometheus"
  test-app:
    image: quay.io/brancz/prometheus-example-app:v0.5.0
    container_name: test-app
    ports:
      - "8080:8080"
  prod-app:
    image: quay.io/brancz/prometheus-example-app:v0.5.0
    container_name: prod-app
    ports:
      - "8081:8080"
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - "./alertmanager.yaml:/etc/alertmanager/alertmanager.yml"
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
      - "--web.external-url=http://localhost:9093"
  mailhog:
    container_name: mailhog
    image: "mailhog/mailhog:v1.0.1"
    ports:
      - "1025:1025"
      - "8025:8025"

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - "grafana_data:/var/lib/grafana"

volumes:
  prometheus_data:
  grafana_data: