services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus-cfg.yaml:/etc/prometheus/prometheus.yml"
      - "prometheus_data:/prometheus"

volumes:
  prometheus_data: